### ISSUE TITLE
Issue Angular GC

### ISSUE THREAD

**Issue by giu-chi-altran-20** [jucasoft/corso-angular-ngrx#14]

**Comment by jucasoft** [comment]
sulla pagina del corso, ho aggiunto un corso base, se ti avanza del tempo, puoi andare avanti con quello.
fammi sapere se hai difficolta.
puoi anche aprire una nuova issue

**Comment by giu-chi-altran-20** [comment]
Ciao, gentilmente puoi fornirmi il link ? Tks in advance.

**Comment by giu-chi-altran-20** [comment]
Volevo inoltre chiedere se questo step 
- https://angular.io/tutorial/toh-pt6
è mandatory per il tutorial Tour of Heros.

Leggevo infatti questo : 
"the In-memory Web API module has nothing to do with HTTP in Angular"

**Comment by jucasoft** [comment]
Ciao, il link si trova in questo punto della pagina del corso:
https://github.com/jucasoft/corso-angular-ngrx#2-angular-routing-app

a breve aggiungero` un paio di link a corsi online, che ho selezionato per voi.

**Comment by jucasoft** [comment]
> Volevo inoltre chiedere se questo step
> 
> * https://angular.io/tutorial/toh-pt6
>   è mandatory per il tutorial Tour of Heros.
> 
> Leggevo infatti questo :
> "the In-memory Web API module has nothing to do with HTTP in Angular"

non e` obbligatorio ma e` di supporto per poter provare i services.
hai avuto difficolta`

**Comment by giu-chi-altran-20** [comment]
Con gli step guidati dal Tutorial al momento non ho incontrato difficoltà...
Sto cercando di affiancare anche una guida teorica per imprimere meglio i concetti ed avere qualche base più solida con ES6 e Typescript.

**Comment by jucasoft** [comment]
hai dei consigli sulla guida teorica da utilizzare?

**Comment by giu-chi-altran-20** [comment]
Ho un libro di Angular 2, un po datato per la verità, si chiama (Sviluppare applicazioni con Angular - Vincenzo Giachina), 
l'ho acquistato un po di anni fa, letto ma mai approfondito. Qui i concetti teorici e pratici di base ci sono tutti.
Integro poi all'occorrenza con queste guide :
https://www.mrw.it/javascript/guida-angular/
https://www.mrw.it/javascript/guida-typescript/

**Comment by jucasoft** [comment]
in questo ambito i libri diventano facilmente obsoleti, ma se parlano di argomenti base sono sempre validi.
ti consiglio di dare un occhio ai corsi di linkedin learning, il primo mese e` gratuito, ci sono contenuti molto validi.
nella ricerca tieni presente anche la data di uscita, giusto per non iniziare un corso gia` vecchio.

**Comment by jucasoft** [comment]
ho aggiunto alcune risorse risorse utili, corsi gratuiti + link
se vuoi restare aggiornato, clicca su watching (in alto a destra vicino a fork)
hai trovato il tempo per andare avanti?
stiamo programmando i nuovi corsi per darvi altro tempo per studiare, questa issue la chiudo, se hai consigli su argomenti da approfondire apri una nuova issue.

**Comment by giu-chi-altran-20** [comment]
Ciao, per informarti che con il proseguimento dei Tutorial sono arrivato a mettere un punto qui  : 
https://angular.io/guide/router-tutorial-toh#route-parameters.
Non riesco a completare, per tempo, entro oggi tutti i Tutorial.

**Comment by jucasoft** [comment]
entro oggi andava completato il primo tutorial, quello che stai finendo era opzionale, di completamento.
non demordere.

**Comment by giu-chi-altran-20** [comment]
ok grazie
