### ISSUE TITLE
dani

### ISSUE THREAD

**Issue by zabatta1992** [jucasoft/corso-angular-ngrx#19]

**Comment by jucasoft** [comment]
sulla pagina del corso, ho aggiunto un corso base, se ti avanza del tempo, puoi andare avanti con quello.
fammi sapere se hai difficolta.
puoi anche aprire una nuova issue

**Comment by jucasoft** [comment]
a che punto sei arrivato?
ho aggiunto alcune risorse risorse utili, corsi gratuiti + link
se vuoi restare aggiornato, clicca su watching (in alto a destra vicino a fork)
questa issue la chiudo
