### ISSUE TITLE
Prova new_issue

### ISSUE THREAD

**Issue by alessiobaroni** [jucasoft/corso-angular-ngrx#2]
Commento prova new issue

**Comment by jucasoft** [comment]
sulla pagina del corso, ho aggiunto un corso base, se ti avanza del tempo, puoi andare avanti con quello.
fammi sapere se hai difficolta.
puoi anche aprire una nuova issue

**Comment by jucasoft** [comment]
ciao, ho aggiunto alcune risorse risorse utili, corsi gratuiti + link
se vuoi restare aggiornato, clicca su watching (in alto a destra vicino a fork)
