### ISSUE TITLE
Paolo

### ISSUE THREAD

**Issue by pneroni** [jucasoft/corso-angular-ngrx#20]

**Comment by jucasoft** [comment]
sulla pagina del corso, ho aggiunto un corso base, se ti avanza del tempo, puoi andare avanti con quello.
fammi sapere se hai difficolta.
puoi anche aprire una nuova issue,
ora copio e incollo questo messaggio a tutti...

**Comment by jucasoft** [comment]
a che puto sei arrivato? 
ho aggiunto alcune risorse risorse utili, corsi gratuiti + link
se vuoi restare aggiornato, clicca su watching (in alto a destra vicino a fork)
per ora chiudo la issue.
