### ISSUE TITLE
ng-rx tutorial

### ISSUE THREAD

**Issue by fabiostevenazzi** [jucasoft/corso-angular-ngrx#21]
fatto tutorial ng-rx
pushato su https://github.com/fabiostevenazzi/angular-ngrx 

Fabio

**Comment by jucasoft** [comment]
hai finito anche questo?
hai delle preferenze su cosa approfondire?
lo hai pubblicato su heroku?

**Comment by fabiostevenazzi** [comment]
si pubblicato e va
https://ngx-crude-fstev.herokuapp.com/coin/main

anche il comando degli unit test su karma mi da errore

C:\Users\fabio\Desktop\test\ngrx-store\ngrx-crude\ngrx-crude>ng test NgrxEntityCrud
Your global Angular CLI version (10.2.0) is greater than your local
version (8.3.24). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
An unhandled exception occurred: Project 'NgrxEntityCrud' does not support the 'test' target.
See "C:\Users\fabio\AppData\Local\Temp\ng-B71JTR\angular-errors.log" for further details.


Quando e se ho tempo faccio quello sul routing

**Comment by jucasoft** [comment]
inutile dire che hai fatto un ottimo lavoro, mi rendo conto che il tempo era veramente poco e dovremmo approfondire molte cose.

i test non sono  mai andati, e` un argomento su cui non sono molto sul pezzo, avrei bisogno di supporto per riuscire a portarli avanti, sei libero? il messaggio che hai sui test non e` un errore, non trova proprio i test... ho da committare la versione con angular 11, ma non trovo il tempo.

ho aggiunto alcune risorse risorse utili, corsi gratuiti + link
se vuoi restare aggiornato, clicca su watching (in alto a destra vicino a fork)
