### ISSUE TITLE
Reactive Form 

### ISSUE THREAD

**Issue by vgrimaldihub** [jucasoft/corso-angular-ngrx#25]
Ciao Luca, 
come avevamo discusso ieri apro una issue.
Il caso di studio che proporrei è un form con molteplici campi(input) popolato in partenza  e modificabile con delle validazioni.

Volendo se ho un po' di tempo posso iniziarlo io.

In particolare se si poteva incentrare su:
- l'utilizzo "minimo" dell'html
- non utilizzare il binding
- creare un form/component riutilizzabile e più "mantenibile" possibile
- utilizzare ed evidenziare le "best practices" 

Grazie.

**Comment by jucasoft** [comment]
ok, in effetti il nostro tuttorial sul reactive form e` molto base, lo hai gia` svolto?
https://github.com/jucasoft/corso-angular-ngrx/blob/main/REACTIVE_FORM.md

**Comment by jucasoft** [comment]
evoluto il reacive form.

**Comment by jucasoft** [comment]
richiesta evasa, fammi sapere se hai altre idee
ciao.
