### ISSUE TITLE
GitHub errore autenticazione da IntelliJ

### ISSUE THREAD

**Issue by Alex7-tr** [jucasoft/corso-angular-ngrx#26]
ciao luca, non riesco a pushare il progetto perché mi dice che ci sono errori. come faccio ?

**Comment by Alex7-tr** [comment]
<img width="938" alt="git" src="https://user-images.githubusercontent.com/73607395/102248604-9f982e80-3f01-11eb-8e0a-9c77d6885479.PNG">

**Comment by jucasoft** [comment]
sembra che manchino le credenziali.
apri intellij
premi Ctrl+Alt+S
seleziona dal pannello di sinista Version Control | GitHub
se trovi un account presente cancellalo, potrebbe essere errato.
clicca sul + per aggiungerne uno
seleziona Login Github
a questo punto si apre il browser per autorizzare intellij ad accedere a github.
completata la procedura, riprova a pushare.
fai sapere.

**Comment by Alex7-tr** [comment]
ciao,

ho riprovato seguendo i comandi, ma mi ripresenta l'errore nonostante le credenziali corrette..

ho fatto come hai detto, ma poi mi fallisce il push come in foto (precedente).

**Comment by jucasoft** [comment]
sembra un problema di autorizzazioni.
apri il terminale e lancia il comando `git remote show origin`
incollami il risultato.

**Comment by Alex7-tr** [comment]
Microsoft Windows [Versione 10.0.19042.630]
(c) 2020 Microsoft Corporation. Tutti i diritti sono riservati.

C:\Users\39334\IdeaProjects\angular-routing-app>git remote show origin
* remote origin
  Fetch URL: https://github.com/jucasoft/angular-routing-app.git
  Push  URL: https://github.com/jucasoft/angular-routing-app.git
  HEAD branch: main
  Remote branch:
    main tracked
  Local branch configured for 'git pull':
    main merges with remote main
  Local ref configured for 'git push':
    main pushes to main (fast-forwardable)

C:\Users\39334\IdeaProjects\angular-routing-app>

**Comment by jucasoft** [comment]
ok, stai provando a caricare le modifiche sul mio repo:
https://github.com/jucasoft/angular-routing-app.git

il tuo e`
https://github.com/Alex7-tr/angular-routing-app.git

dobbiamo cambiare il puntamento.
prima lancia il comando `git remote -v` per vedere a quale repo punti
ora cambiamo il repo remoto con il comando
`git remote set-url origin https://github.com/Alex7-tr/angular-routing-app.git`
rilancia il comando `git remote -v` per vedere se punti al repo corretto
riprova push

fai sapere.

**Comment by Alex7-tr** [comment]
ho eseguito i comandi, ma fallisce uguale.
<img width="944" alt="git2" src="https://user-images.githubusercontent.com/73607395/102347882-55ff2080-3fa1-11eb-8bf4-94e748f442b2.PNG">

**Comment by jucasoft** [comment]
sia come fetch che come push punti al tuo repo, ora il tipo di errore dovrebbe cambiare.

facciamo in modo brutale, 
scarica il tuo repo in una nuova cartella
modifica un file e testa se funziona il push

se funziona il push, cancella dal nuovo progetto il contenuto della cartella src/
copia il contenuto della cartella src/ del vecchio progetto, nel nuovo progetto.
click dx sulla cartella src/, dal menu che appare seleziona git=>add
ripeti click dx su src/, git=>commit directory...
conferma il commit ed esegui il push.

**Comment by Alex7-tr** [comment]
ho committato e pushato....dovresti vederlo ora
