### ISSUE TITLE
TourOfTheHeroes Completato

### ISSUE THREAD

**Issue by zazza123** [jucasoft/corso-angular-ngrx#27]
Ciao Luca, 
     sono Andrea, ho completato il corso 'Tour of the Heroes' di Angular, mi sono permesso di proseguire un pochino aggiungendo anche i superpoteri agli eroi con annessa funzionalità di aggiunta e rimozione.
Sto ancora imparando ad usare GitHub, spero di aver commitato tutto, trovi il mio Fork all'indirizzo: 
- [https://github.com/zazza123/angular-tour-of-heroes](https://github.com/zazza123/angular-tour-of-heroes).

Ho preso anche nota di alcune cose che penso potrebbero aiutare il corso, soprattutto per uno come me che inizia quasi da zero. Magari per quelle potremo sentirci al lavoro.

Strabello comunque Angular!!! Grazie mille.
Un saluto,
Andrea

**Comment by jucasoft** [comment]
Ah! sei tu? ti ho riconosciuto solo quando ho letto "Strabello"
ora controllo il tuo github.

**Comment by jucasoft** [comment]
ottimo lavoro
