### ISSUE TITLE
RoutingApp Completato

### ISSUE THREAD

**Issue by zazza123** [jucasoft/corso-angular-ngrx#28]
Ciao Luca,
     ho completato il corso angular-routing-app. Rispetto al primo, questo era più difficile da seguire.
Ho una domanda, una delle ultime cose che spiegano riguarda la gestione degli URL usando Push o Hash [QUI](https://angular.io/guide/router#locationstrategy-and-browser-url-styles). 
Da quello che mi è parso di capire, sarebbe meglio usare sempre Push perchè in primis è più moderno ed evita di inviare le richieste al server, è corretto? Inoltre, spiegano che quando si crea una applicazione, decidere se usare Push o Hash è importante, secondo te è necessario saperne di più?

Qualora volessi vedere il mio fork puoi trovarlo: [QUI](https://github.com/zazza123/angular-routing-app)
Ho cercato di testare tutto quello che spiegavano all'interno del tutorial inserendo le diverse casistiche di Routing.
Un saluto e grazie mille,
Andrea

**Comment by jucasoft** [comment]
io sapevo che era hash a non inviare richieste al server, in genere vengono utilizzati gli hash per le cosidette "ancore HTML"
un caso pratico di utilizzo degli hash e` quando vuoi aprire una pagina e scorrere fino ad un particolare punto. 
Ad esempio il primo link che hai scritto (nota la posizione dell'hash (#)):
https://angular.io/guide/router#locationstrategy-and-browser-url-styles
dice di aprire la pagina che si trova all'indirizzo:
`https://angular.io/guide/router`
e di scorrere fino all'ancora HTML:
`locationstrategy-and-browser-url-styles`

la parte dell'url che arriva al server e` quella prima dell'hash (#) la parte successiva viene gestita dal browser.

nelle applicaizoni web classiche, ogni url corrisponde ad una pagina http
 - localhost:4200/rotta1/sottorotta (scarica un html)
 - localhost:4200/rotta2/sottorotta (scarica altro html)
 - localhost:4200/rotta3/sottorotta (scarica altro html)

le applicazioni in Angular vengono definite "single-page application (SPA)", vuol dire che tutta l'applicaizone e` un unico html che viene scaricato in una unica soluzione, il cambio pagina viene generato da codice javascript:

 - localhost:4200/rotta1/sottorotta (Angular cattura la chiamata prima che parta per il server, e ridisegna la pagina, utilizzando il componente che abbiamo assegnato alla rotta "rotta1/sottorotta")
 - localhost:4200/rotta2/sottorotta (come sopra)
 - localhost:4200/rotta3/sottorotta (come sopra)

in alcuni vecchi browser, Angular non riesce ad evitare che la rotta arrivi al server, questo genera errori.

**Comment by zazza123** [comment]
Ora mi è più chiara la questione, decisamente. Grazie mille!

**Comment by jucasoft** [comment]
considero chiusa la richiesta
