### ISSUE TITLE
Amaduzzi_test_issue

### ISSUE THREAD

**Issue by riccardoamaduzzi83** [jucasoft/corso-angular-ngrx#3]
test

**Comment by jucasoft** [comment]
sulla pagina del corso, ho aggiunto un corso base, se ti avanza del tempo, puoi andare avanti con quello.
fammi sapere se hai difficolta.
puoi anche aprire una nuova issue

**Comment by jucasoft** [comment]
ho aggiunto alcune risorse risorse utili, corsi gratuiti + link
se vuoi restare aggiornato, clicca su watching (in alto a destra vicino a fork)
hai trovato il tempo per andare avanti?
stiamo programmando i nuovi corsi per darvi altro tempo per studiare, questa issue la chiudo, se hai consigli su argomenti da approfondire apri una nuova issue.
