### ISSUE TITLE
New Issue From Fede

### ISSUE THREAD

**Issue by FedeRWXOnGitHub** [jucasoft/corso-angular-ngrx#4]

**Comment by jucasoft** [comment]
sulla pagina del corso, ho aggiunto un corso base, se ti avanza del tempo, puoi andare avanti con quello.
fammi sapere se hai difficolta.
puoi anche aprire una nuova issue

**Comment by FedeRWXOnGitHub** [comment]
Grazie,
purtroppo non ho molto tempo, comunque cerco di guardarci appena posso.

Fede

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

Da: jucasoft<mailto:notifications@github.com>
Inviato: venerdì 30 ottobre 2020 13:44
A: jucasoft/corso-angular-ngrx<mailto:corso-angular-ngrx@noreply.github.com>
Cc: BOVE Federico<mailto:federico.bove@altran.it>; Author<mailto:author@noreply.github.com>
Oggetto: Re: [jucasoft/corso-angular-ngrx] New Issue From Fede (#4)


sulla pagina del corso, ho aggiunto un corso base, se ti avanza del tempo, puoi andare avanti con quello.
fammi sapere se hai difficolta.
puoi anche aprire una nuova issue

**Comment by jucasoft** [comment]
e` stato un piacere ribeccarti, grazie per la stella....

ho aggiunto alcune risorse risorse utili, corsi gratuiti + link
se vuoi restare aggiornato, clicca su watching (in alto a destra vicino a fork)
hai trovato il tempo per andare avanti?
stiamo programmando i nuovi corsi per darvi altro tempo per studiare, questa issue la chiudo, se hai consigli su argomenti da approfondire apri una nuova issue.
