### ISSUE TITLE
IssueGianlucaCiuffa

### ISSUE THREAD

**Issue by gianlucaciuffa** [jucasoft/corso-angular-ngrx#9]

**Comment by jucasoft** [comment]
sulla pagina del corso, ho aggiunto un corso base, se ti avanza del tempo, puoi andare avanti con quello.
fammi sapere se hai difficolta.
puoi anche aprire una nuova issue

**Comment by gianlucaciuffa** [comment]
> sulla pagina del corso, ho aggiunto un corso base, se ti avanza del tempo, puoi andare avanti con quello.
> fammi sapere se hai difficolta.
> puoi anche aprire una nuova issue

Grazie mille Luca. Spero di poter andare avanti il più possibile.

**Comment by gianlucaciuffa** [comment]
Ciao Luca,
io ho completato tutti i punti da 1 a 6 del "tour of heroes".

Inizialmente avevo capito che anche i successivi corsi ossia 

- Routing (con i sottopunti)
- Building a template driven form
- Web workers

fossero da completare. Puoi confermarmi che anche questi punti vanno sviluppati? Se si, va sviluppato un nuovo progetto o devo continuare sul progetto di tour of heroes? 

Grazie

**Comment by jucasoft** [comment]
Ciao,
nella sezione base, ho aggiunto un tutoria per il routing, 
2) angular-routing-app.

ho aggiunto anche dei link a risorse utiliti.
hai dubbi sul tutorial che hai affrontato?

cliccando su Watching (clicca anche sulla stellina...), nella parte superiore di questo repository, ti arriveranno notifiche relative a modifiche al corso.

vogliamo aggiungere tutorial e tematiche da affrontare al prossimo turno di corsi.

**Comment by gianlucaciuffa** [comment]
Sul tutorial del tour of heoroes no. Sul resto, quello del routing è un po piu fumoso. Sono riuscito ad afferrare i concetti fin dove sono arrivato, ma lo sviluppo della applicazione web non sono riuscito a portarlo avanti. Introduce diverse modifiche e non ti spiega per bene dove vanno inserite alcune direttive.

Ad esempio qui [https://angular.io/guide/router#getting-route-information](https://angular.io/guide/router#getting-route-information) dice di inserire questi import, il costruttore e l'implementazione dell'onInit . Ma su quale componente? In uno nuovo da creare o in uno di quelli gia esistenti? Sul componente di routing?

Personalmente, con il tempo a disposizione sono arrivato fino a qui [https://angular.io/guide/router#accessing-query-parameters-and-fragments](https://angular.io/guide/router#accessing-query-parameters-and-fragments), oltre non sono riuscito.

**Comment by jucasoft** [comment]
> Sul tutorial del tour of heoroes no. Sul resto, quello del routing è un po piu fumoso. Sono riuscito ad afferrare i concetti fin dove sono arrivato, ma lo sviluppo della applicazione web non sono riuscito a portarlo avanti. Introduce diverse modifiche e non ti spiega per bene dove vanno inserite alcune direttive.
> 
> Ad esempio qui https://angular.io/guide/router#getting-route-information dice di inserire questi import, il costruttore e l'implementazione dell'onInit . Ma su quale componente? In uno nuovo da creare o in uno di quelli gia esistenti? Sul componente di routing?

in effetti non indica un componente specifico, hai capito bene; spiega come poter recuperare le informazione della rotta attualmente invocata.
facciamo finta che la totta sia del tipo, http://miarotta.com/home?name=Gianluca
la rotta "home" e` associata al componente home.component.ts e 
nel componete vogliamo recuperare il valore di "name" per poi eseguire una chiamata al BE o stamparlo a video.

> Personalmente, con il tempo a disposizione sono arrivato fino a qui https://angular.io/guide/router#accessing-query-parameters-and-fragments, oltre non sono riuscito.

tieni presente che l'obbiettivo principale era quello di creare contatti tra persone che trattano questa materia.
con la tua richiesta di supporto lo hai raggiunto pienamente.

questa issue la chiudo, non farti problemi ad aprirne di nuove.

**Comment by gianlucaciuffa** [comment]
Grazie mille per il supporto!
